import React from "react";
import{View, Text, StyleSheet} from 'react-native';
import {createNativeStackNavigator} from '@react-navigation/native-stack';
import { NavigationContainer } from '@react-navigation/native';
import SplashScreen from "./src/Auth/SplashScreen";
import Onboarding from "./src/Auth/Onboarding";
import Signin from "./src/Auth/Signin";
import Signup from "./src/Auth/Signup";
import OtpVerification from "./src/Auth/OtpVerification";
import ForgetPass from "./src/Auth/ForgetPass";
import VerifyNewPass from "./src/Auth/VerifyNewPass";
import NewPassword from "./src/Auth/NewPassword";
import HomeScreen from "./src/Home/HomeScreen";
import Donation from "./src/Home/Donation";
import DonationDetail from "./src/Home/DonationDetail";
import Directory from "./src/Home/Directory";
import Announcement from "./src/Home/Announcement";
import AnnouncementDetail from "../Home/AnnouncementDetail";
import Profile from "../Home/Profile";
import Drawer from "../Home/Drawer";
const Stack = createNativeStackNavigator();
